# Generated by Django 5.1.7 on 2025-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arraivuser_groups_arraivuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arraivuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
