# Generated by Django 5.1.7 on 2025-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_arraivuser_is_email_verified_arraivuser_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arraivuser",
            name="google_refresh_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
