# Generated by Django 5.1.7 on 2025-03-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_arraivuser_google_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arraivuser",
            name="google_refresh_token",
        ),
    ]
